# Generated by Django 6.0 on 2026-01-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='F', max_length=1)),
                ('age', models.IntegerField()),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('section_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('badge_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('citizen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrants.citizen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License_Plate',
            fields=[
                ('plate_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('car_model', models.CharField(max_length=30)),
                ('car_make', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrants.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approving_judge', models.CharField(max_length=30)),
                ('citizen_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrants.citizen')),
                ('crime_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrants.crime')),
            ],
        ),
    ]
