# Generated by Django 6.0 on 2026-01-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='citizen_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warrants.citizen'),
        ),
    ]
