# Generated by Django 6.0 on 2026-01-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrants', '0002_alter_officer_citizen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='citizen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warrants.citizen'),
        ),
    ]
