# Generated by Django 6.0 on 2026-01-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrants', '0003_alter_officer_citizen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='race',
            field=models.CharField(choices=[('BLACK', 'Black'), ('EAST_ASIAN', 'East Asian'), ('INDIGENOUS', 'Indigenous / Aboriginal'), ('LATINO', 'Latino / Hispanic'), ('MIDDLE_EASTERN', 'Middle Eastern'), ('SOUTH_ASIAN', 'South Asian'), ('SOUTHEAST_ASIAN', 'Southeast Asian'), ('WHITE', 'White'), ('PNTS', 'Prefer not to say'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
