# Generated by Django 6.0 on 2026-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrants', '0004_alter_citizen_details_alter_citizen_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
