# Generated by Django 6.0 on 2026-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrants', '0005_officer_is_active_officer_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant',
            name='sex',
            field=models.CharField(choices=[('O', 'Open'), ('P', 'Pending'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
