# Generated by Django 6.0 on 2026-02-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warrants', '0006_warrant_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrant',
            old_name='sex',
            new_name='status',
        ),
    ]
