# Generated by Django 6.0 on 2026-02-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrants', '0007_rename_sex_warrant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_plate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='warrants.citizen'),
        ),
    ]
